name: ETL DQ Tests

on:
  push:
  pull_request:

jobs:
  dq-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r TestAutomation/requirements.txt

      - name: Create folders for reports/logs
        working-directory: TestAutomation
        run: |
          mkdir -p TestReport
          mkdir -p LogFile

      - name: Run pytest with HTML report
        working-directory: TestAutomation
        run: |
          pytest

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: etl-dq-html-report
          path: TestAutomation/TestReport/etl_dq_report.html

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: etl-dq-log
          path: TestAutomation/LogFile/etljob.log
